version: '3'
services:
  vue:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh

  flask:
    build: ./backend
    container_name: flask_container
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"